version: '3.9'
networks:
    portal_network:
        driver: bridge
services:
    portal_db:
        image: mysql:5.7
        env_file: env
        restart: unless-stopped
        logging:
          driver: "json-file"
          options:
            max-size: "2048m"
        volumes:
          - /home/igf/igf_portal/portal_v2/mysqlappdb:/var/lib/mysql:rw
        container_name: portal_db
        networks:
          - portal_network
    redis_db:
        image: redis:6.2
        restart: unless-stopped
        container_name: redis_db
        logging:
          driver: "json-file"
          options:
            max-size: "2048m"
        networks:
          - portal_network
    webserver:
        image: imperialgenomicsfacility/igfportal:v0.0.2.1
        env_file: env
        user: "${UID}:${GID}"
        logging:
          driver: "json-file"
          options:
            max-size: "2048m"
        restart: unless-stopped
        links:
          - portal_db
          - redis_db
        depends_on:
          - portal_db
          - redis_db
        volumes:
          - /home/igf/igf_portal/portal_v2/IGFPortal:/github/IGFPortal:ro
          - /home/igf/igf_portal/ssl_cert:/SSL:ro
          - /home/igf/igf_portal/portal_v2/static:/data/static:rw
          - /home/igf/igf_portal/secret/airflow_conf.json:/secret/airflow_conf.json:ro
          - /home/igf/igf_portal/portal_v2/celery_tmp:/TMP_WORK_DIR:rw
        container_name: webserver
        command: ["gunicorn -b 0.0.0.0:8080 --threads 4 server:app"]
        networks:
          - portal_network
    nginx:
        image: nginx:1.23.3
        logging:
          driver: "json-file"
          options:
            max-size: "2048m"
        ports:
          - "80:80"
          - "443:443"
        links:
          - webserver
        depends_on:
          - webserver
        volumes:
          - /home/igf/igf_portal/ssl_cert:/SSL:ro
          - /home/igf/igf_portal/portal_v2/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
          - /home/igf/igf_portal/portal_v2/nginx:/var/nginx/:rw
        container_name: nginx
        restart: unless-stopped
        networks:
          - portal_network
    celery_worker1:
        image: imperialgenomicsfacility/igfportal:v0.0.2.1
        env_file: env
        user: "${UID}:${GID}"
        logging:
          driver: "json-file"
          options:
            max-size: "2048m"
        links:
          - portal_db
          - redis_db
        depends_on:
          - portal_db
          - redis_db
        restart: unless-stopped
        volumes:
          - /home/igf/igf_portal/portal_v2/IGFPortal:/github/IGFPortal:ro
          - /home/igf/igf_portal/secret/airflow_conf.json:/secret/airflow_conf.json:ro
          - /home/igf/igf_portal/portal_v2/celery_tmp:/TMP_WORK_DIR:rw
          - /home/igf/igf_portal/portal_v2/static:/data/static:rw
        container_name: celery_worker1
        command: ["celery -A app.celery worker --loglevel=WARNING"]
        networks:
          - portal_network
    celery_flower:
        image: imperialgenomicsfacility/igfportal:v0.0.2.1
        env_file: env
        restart: unless-stopped
        logging:
          driver: "json-file"
          options:
            max-size: "2048m"
        ports:
          - "5556:5555"
        links:
          - redis_db
          - portal_db
        depends_on:
          - redis_db
          - portal_db
        volumes:
          - /home/igf/igf_portal/portal_v2/IGFPortal:/github/IGFPortal:ro
        container_name: celery_flower
        command: ["celery -A app.celery flower --basic_auth=$${BASIC_AUTH}"]
        networks:
          - portal_network
    adminer:
        image: adminer:latest
        logging:
          driver: "json-file"
          options:
            max-size: "2048m"
        links:
          - portal_db
        ports:
          - "8081:8080"
        restart: unless-stopped
        container_name: adminer
        networks:
          - portal_network