"""empty message

Revision ID: 78b82238be89
Revises: 
Create Date: 2023-04-04 16:09:56.224833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78b82238be89'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experiment_attribute', schema=None) as batch_op:
        batch_op.drop_constraint('experiment_id', type_='unique')
        batch_op.drop_index('experiment_id')

    with op.batch_alter_table('project_attribute', schema=None) as batch_op:
        batch_op.drop_constraint('project_id', type_='unique')
        batch_op.drop_index('project_id')

    with op.batch_alter_table('run', schema=None) as batch_op:
        batch_op.drop_constraint('experiment_id', type_='unique')
        batch_op.drop_index('experiment_id')

    with op.batch_alter_table('run_attribute', schema=None) as batch_op:
        batch_op.drop_constraint('run_id', type_='unique')
        batch_op.drop_index('run_id')

    with op.batch_alter_table('seqrun_attribute', schema=None) as batch_op:
        batch_op.drop_constraint('seqrun_id', type_='unique')
        batch_op.drop_index('seqrun_id')

    with op.batch_alter_table('seqrun_stats', schema=None) as batch_op:
        batch_op.drop_constraint('seqrun_id', type_='unique')
        batch_op.drop_index('seqrun_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seqrun_stats', schema=None) as batch_op:
        batch_op.create_index('seqrun_id', ['seqrun_id', 'lane_number'], unique=False)
        batch_op.create_unique_constraint('seqrun_id', ['seqrun_id', 'lane_number'])

    with op.batch_alter_table('seqrun_attribute', schema=None) as batch_op:
        batch_op.create_index('seqrun_id', ['seqrun_id', 'attribute_name', 'attribute_value'], unique=False)
        batch_op.create_unique_constraint('seqrun_id', ['seqrun_id', 'attribute_name', 'attribute_value'])

    with op.batch_alter_table('run_attribute', schema=None) as batch_op:
        batch_op.create_index('run_id', ['run_id', 'attribute_name', 'attribute_value'], unique=False)
        batch_op.create_unique_constraint('run_id', ['run_id', 'attribute_name', 'attribute_value'])

    with op.batch_alter_table('run', schema=None) as batch_op:
        batch_op.create_index('experiment_id', ['experiment_id', 'seqrun_id', 'lane_number'], unique=False)
        batch_op.create_unique_constraint('experiment_id', ['experiment_id', 'seqrun_id', 'lane_number'])

    with op.batch_alter_table('project_attribute', schema=None) as batch_op:
        batch_op.create_index('project_id', ['project_id', 'attribute_name', 'attribute_value'], unique=False)
        batch_op.create_unique_constraint('project_id', ['project_id', 'attribute_name', 'attribute_value'])

    with op.batch_alter_table('experiment_attribute', schema=None) as batch_op:
        batch_op.create_index('experiment_id', ['experiment_id', 'attribute_name', 'attribute_value'], unique=False)
        batch_op.create_unique_constraint('experiment_id', ['experiment_id', 'attribute_name', 'attribute_value'])

    # ### end Alembic commands ###
