"""empty message

Revision ID: a38c16db0e8d
Revises: 78b82238be89
Create Date: 2023-04-04 16:33:12.174319

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from app.models import LONGTEXTType
from app.models import JSONType
# revision identifiers, used by Alembic.
revision = 'a38c16db0e8d'
down_revision = '78b82238be89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ab_user_role', schema=None) as batch_op:
        batch_op.drop_constraint('user_id', type_='unique')
        batch_op.drop_index('user_id')

    with op.batch_alter_table('experiment', schema=None) as batch_op:
        batch_op.drop_constraint('sample_id', type_='unique')
        batch_op.drop_index('sample_id')

    with op.batch_alter_table('pre_demultiplexing_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('status', sa.Enum('ACTIVE', 'WITHDRAWN', 'UNKNOWN'), server_default='UNKNOWN', nullable=False))

    with op.batch_alter_table('project_analysis_info_data', schema=None) as batch_op:
        batch_op.drop_constraint('project_id', type_='unique')
        batch_op.drop_index('project_id')

    with op.batch_alter_table('project_seqrun_info_data', schema=None) as batch_op:
        batch_op.drop_constraint('project_id', type_='unique')
        batch_op.drop_index('project_id')

    with op.batch_alter_table('raw_analysis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', mysql.INTEGER(unsigned=True), nullable=True))
        batch_op.add_column(sa.Column('pipeline_id', mysql.INTEGER(unsigned=True), nullable=True))
        batch_op.add_column(sa.Column('analysis_name', sa.String(length=120), nullable=False))
        batch_op.alter_column('analysis_yaml',
               existing_type=mysql.LONGTEXT(),
               nullable=True)
        batch_op.alter_column('report',
               existing_type=mysql.TEXT(),
               type_=LONGTEXTType(),
               existing_nullable=True)
        batch_op.drop_index('analysis_tag')
        batch_op.create_unique_constraint(None, ['analysis_name', 'project_id'])
        batch_op.create_foreign_key(None, 'pipeline', ['pipeline_id'], ['pipeline_id'], onupdate='CASCADE', ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'project', ['project_id'], ['project_id'], onupdate='CASCADE', ondelete='SET NULL')
        batch_op.drop_column('analysis_tag')

    with op.batch_alter_table('raw_seqrun', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mismatches', sa.Enum('0', '1', '2'), server_default='1', nullable=True))
        batch_op.add_column(sa.Column('trigger_time', sa.TIMESTAMP(), nullable=True))
        batch_op.add_column(sa.Column('run_config', LONGTEXTType(), nullable=True))

    with op.batch_alter_table('run', schema=None) as batch_op:
        batch_op.drop_constraint('experiment_id', type_='unique')
        batch_op.drop_index('experiment_id')

    with op.batch_alter_table('sample_attribute', schema=None) as batch_op:
        batch_op.drop_constraint('sample_id', type_='unique')
        batch_op.drop_index('sample_id')

    with op.batch_alter_table('sample_index', schema=None) as batch_op:
        batch_op.drop_constraint('sample_index_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'project_index', ['project_index_id'], ['project_index_id'], onupdate='CASCADE', ondelete='SET NULL')

    with op.batch_alter_table('seqrun_stats', schema=None) as batch_op:
        batch_op.drop_constraint('seqrun_id', type_='unique')
        batch_op.drop_index('seqrun_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seqrun_stats', schema=None) as batch_op:
        batch_op.create_index('seqrun_id', ['seqrun_id', 'lane_number'], unique=False)
        batch_op.create_unique_constraint('seqrun_id', ['seqrun_id', 'lane_number'])

    with op.batch_alter_table('sample_index', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('sample_index_ibfk_1', 'project_index', ['project_index_id'], ['project_index_id'])

    with op.batch_alter_table('sample_attribute', schema=None) as batch_op:
        batch_op.create_index('sample_id', ['sample_id', 'attribute_name', 'attribute_value'], unique=False)
        batch_op.create_unique_constraint('sample_id', ['sample_id', 'attribute_name', 'attribute_value'])

    with op.batch_alter_table('run', schema=None) as batch_op:
        batch_op.create_index('experiment_id', ['experiment_id', 'seqrun_id', 'lane_number'], unique=False)
        batch_op.create_unique_constraint('experiment_id', ['experiment_id', 'seqrun_id', 'lane_number'])

    with op.batch_alter_table('raw_seqrun', schema=None) as batch_op:
        batch_op.drop_column('run_config')
        batch_op.drop_column('trigger_time')
        batch_op.drop_column('mismatches')

    with op.batch_alter_table('raw_analysis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('analysis_tag', mysql.VARCHAR(length=50), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('analysis_tag', ['analysis_tag'], unique=False)
        batch_op.alter_column('report',
               existing_type=LONGTEXTType(),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('analysis_yaml',
               existing_type=mysql.LONGTEXT(),
               nullable=False)
        batch_op.drop_column('analysis_name')
        batch_op.drop_column('pipeline_id')
        batch_op.drop_column('project_id')

    with op.batch_alter_table('project_seqrun_info_data', schema=None) as batch_op:
        batch_op.create_index('project_id', ['project_id', 'seqrun_id', 'lane_number', 'index_group_tag'], unique=False)
        batch_op.create_unique_constraint('project_id', ['project_id', 'seqrun_id', 'lane_number', 'index_group_tag'])

    with op.batch_alter_table('project_analysis_info_data', schema=None) as batch_op:
        batch_op.create_index('project_id', ['project_id', 'analysis_id'], unique=False)
        batch_op.create_unique_constraint('project_id', ['project_id', 'analysis_id'])

    with op.batch_alter_table('pre_demultiplexing_data', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('file_path')

    with op.batch_alter_table('experiment', schema=None) as batch_op:
        batch_op.create_index('sample_id', ['sample_id', 'library_name', 'platform_name'], unique=False)
        batch_op.create_unique_constraint('sample_id', ['sample_id', 'library_name', 'platform_name'])

    with op.batch_alter_table('ab_user_role', schema=None) as batch_op:
        batch_op.create_index('user_id', ['user_id', 'role_id'], unique=False)
        batch_op.create_unique_constraint('user_id', ['user_id', 'role_id'])

    # ### end Alembic commands ###
